### ISSUE TITLE
Incohérences dans le déroulement du jeu

### ISSUE THREAD

**Issue by danielleberre** [luffah/Terminus#10]
Dans le premier lieu, il est possible d'interagir avec "Palourde" en exécutant ce fichier (./Palourde).

Dans la suite du jeu, on rencontre le Professeur, avec lequel on doit pouvoir interagir. L'exécution de ./Professeur n'est pas accepté. Il faut faire un cat pour parler, alors que cat est normalement utilisé sur des objets si j'ai bien compris.

Cela me semble incohérent.

**Comment by luffah** [comment]
Il s'agit là d'un problème de représentation des individus et des objets.
Va t'on considérer comme dans le film Tron, que l'individu est un programme, qu'un objet fonctionnel (une clef par exemple) est un programme ou bien s'agit-il de données (l'individu n'est présent que par les données qu'il a laissé, comme l'hologramme de la princess dans Star Wars).

Bref, c'est une question que j'ai mis de côté.
Pour le cas de la Palourde, qui est une françisation arbitraire de 'Shell', le dialogue indique "... parfois je m'execute... " faisant référence à un script. 

C'est donc un point à débattre. :)

**Comment by danielleberre** [comment]
Pour un novice, il faudrait utiliser un verbe particulier pour décrire une commande.

Si parler = exécuter un script la première fois, alors ce comportement doit être maintenu dans l'ensemble du jeu.

Si interagir = cat, alors que ce soit avec un objet ou une personne, ce n'est pas très important. Il suffit juste de faire attention à la description affichée par ls.

Je note que pour Palourde, on peut utiliser à la fois ./Palourde et cat Palourde. Personnellement, je trouve que c'est un problème.

**Comment by daufinsyd** [comment]
Je suis d'accord avec @danielleberre, c'est déroutant de voir qu'une action qui marche une première fois ne marche plus pour les autres fois.

En soit ça ne poserait pas de problème si la notion de permission d'exécution avait été introduite préalablement. 

parler = exécuter me semble pas si mal mais
`./Palourde` qui équivaut à `cat Palourde` induit un risque de mal appréhender ce que fait réellement cat .

**Comment by luffah** [comment]
Je vois la problématique, si on essaye d'entrer le contenu obtenu avec cat dans la ligne de commande, le résultat est incohérent avec celui de l'execution.
Il faudrait au moins que le message soit différent, lorsqu'on execute.

Pour l'instant, je vais enlever ce droit d'execution.
-----
Une politique applicable serait :

S'il s'agit de texte : utiliser `cat`.
Si le texte doit évoluer, il est envisageable de considérer cela comme un programme, mais pas indispensable.
Si l'affichage du texte va de paire avec un changement d'environnement, l'objet devrait être un programme.

Ce qui me fait peur avec cette strategie serait l'utilisation l'objet executable pour les personnagêtees au détriment de `cat`, cependant ce serait aussi l'occasion de fournir une description plus détaillée des personnages, comme s'il s'agissait de l'entête du script.

Qu'en pensez vous ?

**Comment by danielleberre** [comment]
@daufinsyd le comportement de `./Palourde` et de `cat Palourde` est différent. Cela, pourquoi pas.

@luffah cela me convient.

**Comment by luffah** [comment]
voir fichier docs/linux_rules.md.
