### ISSUE TITLE
Procédure pour la traduction

### ISSUE THREAD

**Issue by ludogre** [luffah/Terminus#22]
Bonjour!

J'utilise poedit pour l'édition de fichiers po. Dans terminus, je constate qu'il n'y a pas de fichier catalogue pot . Peut-être est-ce volontaire? Je ne sais pas.

Toujours est-il qu'un fois le fichier po corrigé, rien est indiquée dans le readme pour générer le fichier terminal.dialog.fr.js . :-(

**Comment by Jacques-Olivier-Farcy** [comment]
Bonjour Ludogre,
Nous discutons plutôt sur un Framateam : 
https://framateam.org/signup_user_complete/?id=paznwy85afy3jxy4bc1mi18k4o

**Comment by luffah** [comment]
Voir "Generate missing files"  : il suffit de faire 'make'.

Pour le .pot, c'est un peu lié à une méconnaissance de ce standard. Le but dans l'utilisation de fichiers .po était de donner un interface un peu plus intuitive que le simple fichier texte. 
Le .po est transformer en table (dialog) dans javascript grace à un parser dans nouedejs.
Finalement la table (dialog) est utilisé pour convertir des références avec arguments en texte (phrases). 

Voir gulpfile.js src/js/engine/Gettext.js (et le fichier généré, contenant la table dialog ,dans src/js/_build)

**Comment by ludogre** [comment]
Le .pot est intéressant à utiliser pour un projet multilingue. En effet, il contient tous les termes de l'appli que l'on peut traduire. On parle de catalogue. Ensuite, qui veut peut créer un fichier .po pour une langue donnée et peut charger et mettre à jour les nouveaux termes de son fichier depuis le catalogue. En ce qui me concerne, pour ça, j'utilise poedit ( https://poedit.net/ ) qui me semble bien adapté pour permettre à des gens de traduire sans avoir à mettre la main dans les rouages du logiciel.

Pour ce qui est de la génération du fichier javascritpt, je ne suis pas familié de javascript (mais ça se soigne). Je viens d'installer gulp et npm et leurs nombreuses dépendances ("sudo apt install gulp npm" sur debian). Puis j'ai dû installer gulp-uglify avec npm: npm install gulp-uglify .

Oilà.

C'est partit avec une première contrib' juste pour tester.
