### ISSUE TITLE
VIMproved pour toujours

### ISSUE THREAD

**Issue by ludogre** [luffah/Terminus#27]
Dans la bibliothèque, en consultant la livre VIMproved, il est indiqué qu'il
disparait. Hors, il reste consultable après l'action.

**Comment by luffah** [comment]
Lié à un appel mal contrôlé à un `addListener` sur un Item.  Je transforme ceci en état de jeu : `addState`.  Les Listeners simples devront être ajoutés avec `.setCmdEvent('less',function(context){})`.
