### ISSUE TITLE
L'intriguant panneau indéplaçable

### ISSUE THREAD

**Issue by ludogre** [luffah/Terminus#29]
Dans la bibliothèque, il y a un intriguant panneau avec une source de lumière
derrière. Mais il n'est pas possible de le déplacer. Quand on pénètre dans la
PièceSecrète, il est indiqué qu'elle était derrière le panneau. Ceci laisse à
penser que la PièceSecrète est accessible d'emblée, alors qu'elle devrait
nécessité le déplacement du panneau, et qu'en plus, celui-ci n'est pas
déplaçable.

**Comment by luffah** [comment]
Cet élément n'est pas encore clairement défini.
À l'origine,  il y avait un levier qui s'actionnait tout seul en faisant `less` (ou `cat`) qui ouvrait une pièce secrète où  se trouve le bibliotéquaire. 

> You spot an inconspicuous lever behind the shelves. Curious, you pull it, and a panel slides open to reveal a secret back room.

Avec le mode de jeu à venir, cela se traduirait par : 
`cat Levier`

> Ce levier n'a vraiment rien à faire là. Cela est curieux.

`./Levier`

> Tu tires le levier qui actionne une trappe laissant apparaître une pièce secrète.

L'énigme est un peu trop facile.
Du coups je me suis dit qu'un objet déplaçable placé là par hazard, permettant d'isoler le bibliothècaire... avec pour résolution de sortir la panneau ça pourrait le faire. Mais avec l'énigme du rocher ça fait un peu doublon.

En tout cas, la question principale est : **quelle énigme pour accéder à cette pièce secrète ?**

**Comment by luffah** [comment]
Salut, je t'invites à voir le [wiki](https://github.com/luffah/Terminus/wiki)

**Comment by luffah** [comment]
Le choix a été fait d'utiliser le `./Levier` comme s il s'agissait d'un script.  L'info sera trouvé par le joueur dans un des livres de la bibliothèque.
