### ISSUE TITLE
Tabulation ne fonctionne plus correctement

### ISSUE THREAD

**Issue by ludogre** [luffah/Terminus#31]
Bonjour!

Dans la dernière version de la branche master, lorsqu'on essaie d'obtenir des suggestions à l'aide de la touche tabulation, si on clique sur une des suggestions, la complétion est incohérente. ???

**Comment by luffah** [comment]
La dernière version corrige l'erreur à l'orgine du problème (copier coller abusif dans l la function VTerm -> show_suggestion ). Par contre, j'ajoute un problème avec les polices... la prochaine version incluera une police plus jolie : "Terminal Grotesque".
