### ISSUE TITLE
Erreur de scénario

### ISSUE THREAD

**Issue by daufinsyd** [luffah/Terminus#35]
Au niveau de la clairière (une fois le pont réparé) on est accueilli par le message suivant :

> Tu entres dans Clairière. C'est une clairière couverte d'herbe avec une femme assise sur un rocher, soupirant…
Derrière elle, les ruines d'une maison.

Il faudrait donc renommer _HommeEnPleurs_ en _FemmeEnPleurs_ (ou adapter le texte et le contenu de _HommeEnPleurs_ (naif) )

**Comment by luffah** [comment]
Désolé,  le scénario est figé pour l'instant. 
L'idée est de tout revoir en passant par le wiki d'abord.

**Comment by luffah** [comment]
J'ai remis le texte en mode HommeEnPleurs (sur le git).
