### ISSUE TITLE
Pertinence de l'écriture inclusive

### ISSUE THREAD

**Issue by etnx** [luffah/Terminus#36]
En relisant le texte de Terminus pour le corriger, j'ai remarqué qu'il suivait (parfois) les normes de l'écriture "inclusive" Je soulève ici un problème engendré par le choix de cette démarche pour Terminus, et je propose deux solutions possibles.

**Énonciation et fiction**

Tout d'abord, un petit rappel linguistique.

Dans certains situations d'énonciation, comme par exemple une allocation publique, l'énonciateur ou l'énonciatrice s'adresse à _un ensemble_ d'individus composé d'hommes et de femmes. Le souci d'une parole usant le masculin comme le féminin pour désigner ce public peut s'avérer pertinente, pour marquer sa volonté de ne pas passer sous silence l'existence des femmes notamment.

Dans le cadre particulier de Terminus, la situation d'énonciation est différente : l'ordinateur qui raconte l'histoire, à la façon d'un livre dont vous êtes le héros, s'adresse à _une seule personne_. En outre, le mode d'énonciation est lui aussi différent : Terminus est un _jeu informatique_, plus précisément un jeu de type "first person coder", c'est-à-dire _une fiction_ dans laquelle le joueur ou la joueuse doit s'identifier à un personnage qui en l'occrurence évolue dans un univers _fantasy_.

Cette identification au personnage est essentielle dans la construction du pacte fictionnel. Sans cette identification, le _tu_ énoncé par l'ordinateur-narrateur ne fonctionnerait plus : le joueur ou la joueuse ne pourrait plus faire semblant d'être le personnage auquel s'adresse l'ordinateur.

**Écriture inclusive versus pacte fictionnel**

Dans ce contexte particulier, l'écriture dite inclusive — par l'utilisation des points médians et par l'emploi de la double flexion — présente un inconvénient majeur : elle rappelle constamment que le jeu s'adresse à un _ensemble_ d'hommes et de femmes.

Or, le joueur ou la joueuse, dans le cadre du pacte fictionnel vidéoludique, souhaite au contraire instaurer une relation personnelle _unique_ avec l'interface de jeu. En s'adressant explicitement à différents individus, l'ordinateur-narrateur instaure un retour au réel (celui de la multiplicité des destinataires) qui rompt le pacte fictionnel au détriment du plaisir du jeu.

L'identification au personnage est alors suspendue et l'émotion ressentie face aux péripéties de l'histoire s'amoindrit.

**Possibilités de l'imaginaire**

Il existe pourtant d'autres solutions que l'écriture inclusive pour contourner l'hégémonie du masculin que nous constatons dans le jeu vidéo.

Puisque l'identification dans le jeu est simulée, les caractéristiques du personnage ne sont aucunement obligées de correspondre avec celles du joueur ou de la joueuse. Qu'il s'agisse du sexe, de l'ethnie, de la religion, du tempérament, des goûts vestimentaires… n'importe quelle caractéristique imaginaire peut être interprétée par le joueur ou la joueuse et enrichir d'autant le pacte fictionnel.

**Solutions proposées**

En pratique, je vois trois solutions au problème posé par le choix de l'écriture inclusive :

1. Revenir à l'état antérieur et adopter un genre grammatical exclusivement masculin. Solution simple, assez habitelle et efficace : le public mâle — qui est majoritaire parmi les "informaticiens" — s'identifiera spontanément au personnage.

2. Proposer de choisir en début de partie entre un personnage féminin et un personnage masculin. Ainsi, les joueuses pourront choisir d'incarner un personnage masculin ou féminin selon leur envie, et les joueurs pourront eux aussi choisir entre ces deux options (je n'aborde pas la question de la transidentité…). Les concepteurs et/ou conceptrices du jeu évitent ainsi d'imposer un sexe et permettent au public d'effectuer son propre  choix.

3. Imposer le choix d'un personnage féminin. En effet, si la motivation à l'origine de l'écriture "inclusive" dans Terminus était d'accorder une visibilité habitellement refusée aux femmes, alors autant assumer cet engagement. Dans le cadre du pacte fictionnel, incarner un personnage féminin lorsqu'on est un homme est parfaitement possible et s'avère compatible avec le succès auprès du public, comme en témoigne le célèbre _Tomb Raider_ et son héroïne Lara Croft.

Je préconise donc la troisième solution, qui présente l'avantage de démarquer Terminus par rapport aux autres jeux — les personnages principaux féminins sont rares dans le jeu vidéo — et de bousculer les stéréotypes concernant l'informatique (un truc de barbus). Toute création est un parti-pris, autant le reconnaître et l'affirmer en proposant d'incarner une héroïne.

**Comment by luffah** [comment]
Merci, pour ton explication éclairée.
Je n'ai pas encore de réponse toute faite à ce problème.

Je trouve que laisser la liberté du genre du·de la protagoniste tout au long du jeu y apporte un plus. 
Voici différents points de réflexion qui me confortent dans cette idée.

##### Une version originale avec protagoniste agenre
Dans la version 'MIT' du jeu, le genre n'était pas marqué pour la protagoniste.
C'était plus simple en Anglais, car le genre pour le 'JE'  y apparaît très peu (surtout dans la forme possessive). 

##### Un problème liées aux questions qu'on se posera en cours de jeu
Le choix du genre des protagonistes d'un jeu est lié au choix de leur personnalité, ce qui est aussi le cas de l'âge ou encore des vêtements (qui reflètent des paramètres sociaux et pratiques). 

Pour avoir jouer à des jeux avec protagoniste masculin, des jeux avec protagoniste féminin, des jeux avec genre en option  et des jeux avec des protagoniste agenre, j'ai l'impression que les questions que se posent la personne en train de jouer sont différentes :
* Dans le cas où le choix du genre se fait avant le début du jeu, le·la joueuse peut se dire que les capacités de le·la protagoniste seront différentes en fonction de son sexe masculin (associé à un stéréotype de force brute) ou féminin (associé à un stéréotype de pouvoir magique de soin). Dans ce cas, pour notre jeu, le·la joueuse doit faire un choix qui ne va rien apporté au scénario.
* Dans le cas où le personnage principale est de genre évident, par exemple point&click "Fran Bow", on constate que certains personnages réagisse selon le genre de l'héroïne. On ne se pose pas trop de question sur le genre, on ne fait qu'absorber des constats de genre émis par le jeu.
* Dans le cas où le personnage principale n'a pas de genre, par exemple dans "Undertale", on constate surtout les autres différences et on se pose la question "de quel genre croit t'on que je suis ?" seulement dans les cas de séduction. D'ailleurs cette absence de genre apporte un élément de plus à l'intrigue.  

##### Le genre des personnages non-jouables importe énormément
Je pense que ce sont surtout les personnages non jouables qui ont de l'importance dans les stéréotypes émis. En effet, le genre de la personne qui prend des décisions n'est autre que le genre de la joueuse.

À côté de cela,  il me semble important que le personnage principal n'est pas de genre (dans la phase d'installation du scénario) pour écarter la mise en place de stéréotype avant le début du jeu. C'est une sorte de question d'hygiène.

#####  L'écriture inclusive dans le jeu pour donner de la visibilité à cette pratique
L'idée de l'écriture inclusive est d'écrire des textes officiels/militants qui s'adresse à tou·te·s, mettant en visibilité les femmes / le genre féminin.
Même si on arrive pas à  l'utiliser tout au long du jeu pour des problèmes d'indentification. Il me semble intéressant d'en garder l'usage pour des textes génériques, tels que le manuel d'utilisation des commandes, afin d'ajouter de la visibilité à cette forme d'écriture .

##### D'autres façons de jouer avec un genre de personnage
Dans les bases du scénario,  le·la protagoniste est transféré·e dans un monde alternatif, sous une autre enveloppe,  avec des moyens de communication limités.
Il est donc possible de jouer avec un genre indéfini.
Les personnages non-jouables peuvent , selon leur personnalité, attribuer ou demander son genre au·à la protagoniste.

**Comment by luffah** [comment]
Excellent. Je crois qu'on arrive à un point d'entente. :)  Effectivement, l'utilisation du passé composé au moment de traduire la version originale était très maladroite.  
Il serait même plus malin d'utiliser une écriture inclusive visible – dans le sens qu'on remarque le "é·e" –  pour les scènes les plus marquantes du scénario; et un écriture inclusive discrète – utilisation du présent et de synonymes– pour ce qui est redondant.

**Comment by luffah** [comment]
Ceci est un parti pris pour ce projet. Si il n'a pas de formulation claire et inclusive sans utiliser le "é-e", on utilise le "é-e". L'impossibilité de ne pas attribuer un genre à une action est, en quelque sorte, considéré comme un bug dans la langue (à contourner avec des adjuvants aussi moches soient-ils).

**Comment by luffah** [comment]
La formulation n'est pas encore parfaite, mais ce choix est énoncé dans le wiki https://github.com/luffah/Terminus/wiki/R%C3%A8gles-de-contributions
