### ISSUE TITLE
grep password

### ISSUE THREAD

**Issue by pbettens** [luffah/Terminus#41]
bonjour

(merci pour le jeu, c'est très cool)

je ne parviens pas à « écrire le bon grep » pour l'obtention du mot de passe dans `FichiersNoyaux/PlusDeFichiersNoyau` et j'essaie pléthore de commandes… mais rien n'y fait. j'ai tenté:

- grep password= *.txt
- grep password *.txt
- grep password= L.txt   M.txt  Q.txt  R.txt  S.txt  T.txt  U.txt  V.txt  W.txt  
- grep password= L.txt
- *(tous les autres un par un)*
- *(tout ça sans le =)*

pouvez-vous me dire s'il y a une erreur ou si je dois simplement persévérer ;-)

**Comment by luffah** [comment]
il s'agit bien d'une erreur, qui sera résolu au prochain merge avec la branche 'develop'.

**Comment by luffah** [comment]
Voir commit [cd5cbae2158998bd806ad7ef48c0a46ca7df0452](https://github.com/luffah/Terminus/commit/cd5cbae2158998bd806ad7ef48c0a46ca7df0452) qui a des impacts fonctionnel sur de nombreuses parties du jeu.

Les changements réalisés sur 'grep' – et les autres commandes – permettent un comportement complexe sans surcharger l'interface de jeu, et peuvent être illustré comme suit : 
```
> cat Fichier
 Ce fichier est trop long. Et si tu utilisais 'grep'.

> cat Fiche
Bla bla
Bouh

> grep passwo Fichier
Le mot de passe est 'password'.

> grep bla Fiche
Bla bla
```

**Comment by luffah** [comment]
Merge fait
