### ISSUE TITLE
sudo pas utilisable

### ISSUE THREAD

**Issue by cl-parsons** [luffah/Terminus#42]
J'ai réussi à accéder à la commande sudo en greppant password dans les fichiers du noyau. Néanmoins, je ne peut pas l'utiliser, même pour faire un "pkill -9 Magus", ce qui je pense résolverait le problème. Aussi, quand j'ai *touch* une Maison pour l'homme en pleur, je ne peut plus la supprimmer. Après avoir fait ça je me suis dit que j'aurais pu mkdir un Maison et mv l'HommeEnPleurs dans la maison.

Quand je fais help, la ligne sudo affiche *sudo_help*, comme si c'était une variable inconnue.
La commande man sudo ne marche pas non plus.

**Comment by luffah** [comment]
La fin de la version béta contient plusieurs bugs de ce genre. C'est en cours de révision (branche develop), mais ça demande du temps.

Merci pour les retours.

---------------
N.B. :  Dans l'univers de Terminus :
-  'pkill -9 Magus' ne resoud pas le problème; pkill retournerait une erreur.
- normalement, la maison ne peut pas être 'touch'.

**Comment by luffah** [comment]
Le sudo est utilisable pour le but donné dans le scénario original du jeu et est utilisable avec la version utilisant le framework (dépend de la bonne attribution des droits).
