### ISSUE TITLE
Grep password et sudo 

### ISSUE THREAD

**Issue by astalush** [luffah/Terminus#44]
Bonjour. Je n'arrive pas a passer le jeu au niveau du grep password= *.txt or grep password= L.txt ni rien. J'ai essayé de chercher avec grep password= Q.txt or n'importe quel fichier txt, ca ne fonctionne pas. Meme en utilisant sudo cat Certificat et en tapant le MDP (IH***) ca ne fonctionne pas. J'ai vu sur github que vous avez mis a jour il y a deux mois le fichier https://github.com/luffah/Terminus/blob/master/src/js/terminus.level2.js concernant la commande grep. Le jeu etait mis a jour ou pas? Comment on peut reussir passer cette etape? Merci pour votre aide.
J'ai mis deux imprime ecran ici : https://images2.imgbox.com/c6/d2/AHwE4vFj_o.png et https://images2.imgbox.com/22/ab/uBZKCIuI_o.png

**Comment by luffah** [comment]
Bonjour le jeu n'a pas été mis à jour à ce moment là. Désolé pour la gène occasionnée.
Un mise à jour a été passée en début de semaine.
