### ISSUE TITLE
Issue with GREP : to implement without jquery

### ISSUE THREAD

**Issue by luffah** [luffah/Terminus#7]
as it's said

**Comment by luffah** [comment]
fait.

**Comment by ludogre** [comment]
Euh, En ce qui me concerne, grep ne fonctionne toujours pas sur la branche master. J'ai zappé quelque chose?

**Comment by luffah** [comment]
Le problème réapparait suite à l'ajout des propriétés read write execute  (en remplacement à l'attribution nominative des commandes) sur les lieux objet et personnages. On rouvre le bug, même si le problème, n'a plus rien à voir avec JQuery.

**Comment by luffah** [comment]
Fait ! le problème était lié un test obsolète : 
* avant ajout des propriété rwx et de la notion "utilisateur": on se posait la question "la commande est-elle utilsable ?"
* après cet ajout : on se pose maintenant la question (avant d'appeler la commande) "l'utilisateur courant appartient t'il au groupe authorisé à l'utiliser"
